### ISSUE TITLE
KafkaConsumer crashes when fused with other kafkaconsumers

### ISSUE THREAD

**Issue by jms90h5** [IBMStreams/streamsx.kafka#102]
I have an application that works fine when all the kafka consumers are in separate PE's.  But when I fuse multiple kafkaconsumers into a single PE I get this exception:

`17 Jul 2018 15:50:18.182 [6029] ERROR #splapptrc,J[0],P[0],BarSessionCommonF M[LogContext.java:org.apache.kafka.common.utils.LogContext$KafkaLogger.error:296]  - [Consumer clientId=Xj2jFUyOCRrecjQ9U9jzVb4RIzaTpxnXXLkKtkLjuSQO, groupId=mygroup] Heartbeat thread for group mygroup failed due to unexpected error
17 Jul 2018 15:50:18.185 [6029] ERROR #splapptrc,J[0],P[0],BarSessionCommonF M[?:?:0]  - org.apache.kafka.common.KafkaException: Error registering mbean kafka.consumer:type=consumer-node-metrics,client-id=Xj2jFUyOCRrecjQ9U9jzVb4RIzaTpxnXXLkKtkLjuSQO,node-id=node-2
17 Jul 2018 15:50:18.185 [6029] ERROR #splapptrc,J[0],P[0],BarSessionCommonF M[?:?:0]  - 	at org.apache.kafka.common.metrics.JmxReporter.reregister(JmxReporter.java:164)
17 Jul 2018 15:50:18.185 [6029] ERROR #splapptrc,J[0],P[0],BarSessionCommonF M[?:?:0]  - 	at org.apache.kafka.common.metrics.JmxReporter.metricChange(JmxReporter.java:82)
17 Jul 2018 15:50:18.186 [6029] ERROR #splapptrc,J[0],P[0],BarSessionCommonF M[?:?:0]  - 	at org.apache.kafka.common.metrics.Metrics.registerMetric(Metrics.java:535)
17 Jul 2018 15:50:18.186 [6029] ERROR #splapptrc,J[0],P[0],BarSessionCommonF M[?:?:0]  - 	at org.apache.kafka.common.metrics.Sensor.add(Sensor.java:230)
17 Jul 2018 15:50:18.186 [6029] ERROR #splapptrc,J[0],P[0],BarSessionCommonF M[?:?:0]  - 	at org.apache.kafka.common.metrics.Sensor.add(Sensor.java:216)
17 Jul 2018 15:50:18.187 [6029] ERROR #splapptrc,J[0],P[0],BarSessionCommonF M[?:?:0]  - 	at org.apache.kafka.common.network.Selector$SelectorMetrics.maybeRegisterConnectionMetrics(Selector.java:978)
17 Jul 2018 15:50:18.187 [6029] ERROR #splapptrc,J[0],P[0],BarSessionCommonF M[?:?:0]  - 	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:436)
17 Jul 2018 15:50:18.187 [6029] ERROR #splapptrc,J[0],P[0],BarSessionCommonF M[?:?:0]  - 	at org.apache.kafka.common.network.Selector.poll(Selector.java:398)
17 Jul 2018 15:50:18.187 [6029] ERROR #splapptrc,J[0],P[0],BarSessionCommonF M[?:?:0]  - 	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:460)
17 Jul 2018 15:50:18.188 [6029] ERROR #splapptrc,J[0],P[0],BarSessionCommonF M[?:?:0]  - 	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:238)
17 Jul 2018 15:50:18.188 [6029] ERROR #splapptrc,J[0],P[0],BarSessionCommonF M[?:?:0]  - 	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.pollNoWakeup(ConsumerNetworkClient.java:275)
17 Jul 2018 15:50:18.188 [6029] ERROR #splapptrc,J[0],P[0],BarSessionCommonF M[?:?:0]  - 	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$HeartbeatThread.run(AbstractCoordinator.java:934)
17 Jul 2018 15:50:18.189 [6029] ERROR #splapptrc,J[0],P[0],BarSessionCommonF M[?:?:0]  - Caused by: javax.management.InstanceAlreadyExistsException: kafka.consumer:type=consumer-node-metrics,client-id=Xj2jFUyOCRrecjQ9U9jzVb4RIzaTpxnXXLkKtkLjuSQO,node-id=node-2
17 Jul 2018 15:50:18.189 [6029] ERROR #splapptrc,J[0],P[0],BarSessionCommonF M[?:?:0]  - 	at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:449)
17 Jul 2018 15:50:18.189 [6029] ERROR #splapptrc,J[0],P[0],BarSessionCommonF M[?:?:0]  - 	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1910)
17 Jul 2018 15:50:18.190 [6029] ERROR #splapptrc,J[0],P[0],BarSessionCommonF M[?:?:0]  - 	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:978)
17 Jul 2018 15:50:18.190 [6029] ERROR #splapptrc,J[0],P[0],BarSessionCommonF M[?:?:0]  - 	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:912)
17 Jul 2018 15:50:18.190 [6029] ERROR #splapptrc,J[0],P[0],BarSessionCommonF M[?:?:0]  - 	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:336)
17 Jul 2018 15:50:18.190 [6029] ERROR #splapptrc,J[0],P[0],BarSessionCommonF M[?:?:0]  - 	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:534)
17 Jul 2018 15:50:18.191 [6029] ERROR #splapptrc,J[0],P[0],BarSessionCommonF M[?:?:0]  - 	at org.apache.kafka.common.metrics.JmxReporter.reregister(JmxReporter.java:162)
17 Jul 2018 15:50:18.191 [6029] ERROR #splapptrc,J[0],P[0],BarSessionCommonF M[?:?:0]  - 	... 11 more`

**Comment by rnostream** [comment]
I'll have a look at this issue. Which toolkit version are you actually using. I assume the last one, correct?

**Comment by jms90h5** [comment]
Correct.

**Comment by rnostream** [comment]
I forced same behavior when putting consumers in same PE and giving all consumers the same client.id. The exception is caused internally in the Kafka client itself when trying registering an MBean for the KafkaClient for Kafka provided metering (not Streams/Operator). The MBean is registered by using the client.id. So registering all clients with same id will fail.

I suppose you gave an explicit client.id to all Consumers (e.g. configure one operator and create multiple instances with UDP). Don't used explicit client.id definition here.

**Comment by rnostream** [comment]
If you use UDP and want to have an explicit set client.id you can use the getChannel() function to add the channel to the string you set as client.id parameter. Setting the client.id in property file will not work as you can't change it according to the UDP channel.

**Comment by RolefH** [comment]
I'm going to add this restriction to the spldoc of the toolkit for the next release.
- use clientId parameter with added channel number, or
- don't specify a client ID at all, so that each operator instance creates its own random Id.

**Comment by RolefH** [comment]
A different option would be to append the UDP channel number to the client.id property by the operator itself if
a) the operator is within a parallel region, i.e. `int getChannel()` returns a valid channel number.
b) the client-ID is either operator parameter or set up as property in config file or app option

**Comment by RolefH** [comment]
The bug affects both KafkaProducer and KafkaConsumer
