### ISSUE TITLE
KafkaConsumer throws NullPointerException when topic is missing

### ISSUE THREAD

**Issue by RolefH** [IBMStreams/streamsx.kafka#121]
When a the subscribed topic is missing, and cannot be automatically created because `auto.create.topics.enable` in the broker is `false`, the KafkaConsumer throws a NullpointerException:

```
Exception in thread "Thread-12" java.lang.NullPointerException
        at com.ibm.streamsx.kafka.clients.consumer.AbstractKafkaConsumerClient.lambda$getAllTopicPartitionsForTopic$1(AbstractKafkaConsumerClient.java:962)
        at com.ibm.streamsx.kafka.clients.consumer.AbstractKafkaConsumerClient$$Lambda$16.000000000C7F2F40.accept(Unknown Source)
        at java.util.ArrayList.forEach(ArrayList.java:1268)
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1091)
        at com.ibm.streamsx.kafka.clients.consumer.AbstractKafkaConsumerClient.getAllTopicPartitionsForTopic(AbstractKafkaConsumerClient.java:960)
        at com.ibm.streamsx.kafka.clients.consumer.CrKafkaConsumerGroupClient.subscribeToTopics(CrKafkaConsumerGroupClient.java:362)
        at com.ibm.streamsx.kafka.operators.AbstractKafkaConsumerOperator.initialize(AbstractKafkaConsumerOperator.java:621)
        at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter.initialize(OperatorAdapter.java:745)
        at com.ibm.streams.operator.internal.jni.JNIBridge.<init>(JNIBridge.java:277)
```

In general, a NullPointerException should never be thrown. A meaningfull message should be logged.

**Comment by RolefH** [comment]
resolved in v1.5.1
