### ISSUE TITLE
Resetting from checkpoint will fail when sequence id is >1000

### ISSUE THREAD

**Issue by thomas-mattsson** [IBMStreams/streamsx.kafka#171]
All our jobs (using streamsx.messagehub toolkit 2.0.1) are currently failing to reset from checkpoints with the following error:
```Exception in thread "Thread-72" com.ibm.streamsx.kafka.KafkaOperatorResetFailedException: timeout receiving OFFSET.MAP.MERGE.COMPLETE JMX notification for 1,192/5 from MXBean com.ibm.streamsx.kafka:groupIdHash=N612357509,type=consumergroup in JCP. Current timeout is 15,000 milliseconds.
	at com.ibm.streamsx.kafka.clients.consumer.CrKafkaConsumerGroupClient.createSeekOffsetMap(CrKafkaConsumerGroupClient.java:1045)
	at com.ibm.streamsx.kafka.clients.consumer.CrKafkaConsumerGroupClient.resetPrepareDataBeforeStopPolling(CrKafkaConsumerGroupClient.java:909)
	at com.ibm.streamsx.kafka.clients.consumer.CrKafkaConsumerGroupClient.onReset(CrKafkaConsumerGroupClient.java:481)
	at com.ibm.streamsx.kafka.operators.AbstractKafkaConsumerOperator.reset(AbstractKafkaConsumerOperator.java:1100)
```

When enabling debug tracing we get the explanation in the following error:
```07 Aug 2019 08:15:44.717+0000 [49763] INFO #splapptrc,J[346],P[940],MHRawMessageSourceStream.RawMessageSourceStream[0] M[CrKafkaConsumerGroupClient.java:com.ibm.streamsx.kafka.clients.consumer.CrKafkaConsumerGroupClient.handleNotification:268]  - handleNotification() [SUBSCRIBED]; notification = javax.management.Notification[source=com.ibm.streamsx.kafka:groupIdHash=N612357509,type=consumergroup][type=OFFSET.MAP.MERGE.COMPLETE][message={"consolidatedOffsetMap":[[{"topic":"raw-events","partition":0,"toString":"raw-events-0"},3541],[{"topic":"edge-hazards","partition":0,"toString":"edge-hazards-0"},71],[{"topic":"notifications","partition":0,"toString":"notifications-0"},1456]],"contributedOperatorNames":["MHRawMessageSourceStream.source[0].KafkaSourceStream"],"nExpectedContributions":1,"nContributions":1,"complete":true,"key":{"sequenceId":1,192,"resetAttempt":-1,"toString":"1,192/21"}}]
07 Aug 2019 08:15:44.725+0000 [49763] DEBUG  M[ClientNotifForwarder.NotifFetcher-run:?:-1]  - Failed to forward a notification to a listener
07 Aug 2019 08:15:44.726+0000 [49763] DEBUG  M[?:?:0]  - com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 418 path $.key.192
07 Aug 2019 08:15:44.726+0000 [49763] DEBUG  M[?:?:0]  - com.google.gson.Gson.fromJson(Gson.java:902)
07 Aug 2019 08:15:44.726+0000 [49763] DEBUG  M[?:?:0]  - com.google.gson.Gson.fromJson(Gson.java:852)
07 Aug 2019 08:15:44.727+0000 [49763] DEBUG  M[?:?:0]  - com.google.gson.Gson.fromJson(Gson.java:801)
07 Aug 2019 08:15:44.727+0000 [49763] DEBUG  M[?:?:0]  - com.google.gson.Gson.fromJson(Gson.java:773)
07 Aug 2019 08:15:44.727+0000 [49763] DEBUG  M[?:?:0]  - com.ibm.streamsx.kafka.clients.consumer.CrKafkaConsumerGroupClient.handleNotification(CrKafkaConsumerGroupClient.java:270)
07 Aug 2019 08:15:44.727+0000 [49763] DEBUG  M[?:?:0]  - com.sun.jmx.remote.opt.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:421)
07 Aug 2019 08:15:44.728+0000 [49763] DEBUG  M[?:?:0]  - com.sun.jmx.remote.opt.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:395)
07 Aug 2019 08:15:44.728+0000 [49763] DEBUG  M[?:?:0]  - java.lang.Thread.run(Thread.java:812)
```

Turns out when the sequence id passes 1000 the json generation is incorrectly adding number separators ( `1,000`).

**Comment by thomas-mattsson** [comment]
Have a fix ready, preparing PR

**Comment by thomas-mattsson** [comment]
https://github.com/IBMStreams/streamsx.kafka/pull/172

**Comment by thomas-mattsson** [comment]
@RolefH, can you have a look at this? It's a serious blocker for us. See PR #172 for fix.

**Comment by RolefH** [comment]
corrected in https://github.com/IBMStreams/streamsx.kafka/releases/tag/v2.0.1
