### ISSUE TITLE
Too many libs

### ISSUE THREAD

**Issue by schulz2** [IBMStreams/streamsx.kafka#26]
In project's sub-directory ./opt/downloaded reside too many libraries. The following
libs are downloaded but not really used:
gson-2.8.0.jar
jopt-simple-5.0.3.jar
kafka_2.10-0.10.2.0.jar
log4j-1.2.17.jar
lz4-1.3.0.jar
metrics-core-2.2.0.jar
scala-library-2.10.6.jar
slf4j-api-1.7.21.jar
slf4j-log4j12-1.7.21.jar
snappy-java-1.1.2.6.jar
zkclient-0.10.jar
zookeeper-3.4.9.jar

**Comment by cancilla** [comment]
I updated the depenendencies in the build.gradle to `kafka-clients`. I also removed the dependency on gson as this is no longer used in the code. This reduces the list to the follow JARs. 

(It's important to note that some of these libs are dependencies required by `kafka-clients`.)

 * commons-lang3-3.5.jar  
 * guava-21.0.jar  
 * kafka-clients-0.10.2.1.jar  
 * lz4-1.3.0.jar  
 * slf4j-api-1.7.21.jar  
 * snappy-java-1.1.2.6.jar

**Comment by schulz2** [comment]
I'm sorry for this, but it seems that we need to put 'slf4j-log4j12-1.7.21.jar' back into the
libs collection, too, as now I get the following exception during test:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "Thread-13" java.lang.NullPointerException
	at com.ibm.streamsx.kafka.clients.AbstractKafkaClient.getSerializer(AbstractKafkaClient.java:28)
	at com.ibm.streamsx.kafka.clients.producer.KafkaProducerClient.<init>(KafkaProducerClient.java:38)
	at com.ibm.streamsx.kafka.clients.producer.AtLeastOnceKafkaProducerClient.<init>(AtLeastOnceKafkaProducerClient.java:16)
	at com.ibm.streamsx.kafka.operators.AbstractKafkaProducerOperator.initProducer(AbstractKafkaProducerOperator.java:273)
	at com.ibm.streamsx.kafka.operators.AbstractKafkaProducerOperator.initialize(AbstractKafkaProducerOperator.java:257)
	at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter.initialize(OperatorAdapter.java:736)
	at com.ibm.streams.operator.internal.jni.JNIBridge.<init>(JNIBridge.java:274)

**Comment by cancilla** [comment]
The NPE is due to #30 and not related to the SLF4J warning. 

I added the slf4j-log4j library back to the classpath to remove the warning from the logs.
