### ISSUE TITLE
KafkaConsumer NPE when consistent region is enabled

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.kafka#48]
```
04 Oct 2017 07:14:22.213 [8302] ERROR #splapptrc,J[10],P[67],KafkaStream M[AbstractKafkaConsumerOperator.java:com.ibm.streamsx.kafka.operators.AbstractKafkaConsumerOperator$1.run:387]  - Operator error
04 Oct 2017 07:14:22.214 [8302] ERROR #splapptrc,J[10],P[67],KafkaStream M[?:?:0]  - java.lang.RuntimeException: java.lang.NullPointerException
04 Oct 2017 07:14:22.215 [8302] ERROR #splapptrc,J[10],P[67],KafkaStream M[?:?:0]  - 	at com.ibm.streamsx.kafka.operators.AbstractKafkaConsumerOperator.produceTuples(AbstractKafkaConsumerOperator.java:440)
04 Oct 2017 07:14:22.215 [8302] ERROR #splapptrc,J[10],P[67],KafkaStream M[?:?:0]  - 	at com.ibm.streamsx.kafka.operators.AbstractKafkaConsumerOperator.access$000(AbstractKafkaConsumerOperator.java:45)
04 Oct 2017 07:14:22.215 [8302] ERROR #splapptrc,J[10],P[67],KafkaStream M[?:?:0]  - 	at com.ibm.streamsx.kafka.operators.AbstractKafkaConsumerOperator$1.run(AbstractKafkaConsumerOperator.java:385)
04 Oct 2017 07:14:22.216 [8302] ERROR #splapptrc,J[10],P[67],KafkaStream M[?:?:0]  - 	at java.lang.Thread.run(Thread.java:785)
04 Oct 2017 07:14:22.216 [8302] ERROR #splapptrc,J[10],P[67],KafkaStream M[?:?:0]  - 	at com.ibm.streams.operator.internal.runtime.OperatorThreadFactory$2.run(OperatorThreadFactory.java:137)
04 Oct 2017 07:14:22.216 [8302] ERROR #splapptrc,J[10],P[67],KafkaStream M[?:?:0]  - Caused by: java.lang.NullPointerException
04 Oct 2017 07:14:22.216 [8302] ERROR #splapptrc,J[10],P[67],KafkaStream M[?:?:0]  - 	at com.ibm.streamsx.kafka.operators.AbstractKafkaConsumerOperator.produceTuples(AbstractKafkaConsumerOperator.java:428)
04 Oct 2017 07:14:22.217 [8302] ERROR #splapptrc,J[10],P[67],KafkaStream M[?:?:0]  - 	... 4 more

```

**Comment by cancilla** [comment]
Fixed via commit 5eef2b0
